### PR TITLE
Make AdapteeCollection compatible with List interface,

### PR DESCRIPTION
**Pull request by raycoarana**
Make AdapteeCollection&lt;T&gt; compatible with List&lt;T&gt; interface, so any class implementing a List could be used as an AdapteeCollection by simply implementing it. For example, ListAdapteeCollection&lt;T&gt; can be now implemented with less code.

### CODE REVIEW

**Comment by pedrovgs** [comment]
Thanks for the pull request @raycoarana!! Extend from ArrayList instead of just use a similar interface is a good idea! 

Please, review the build because your PR hasn't blue ball :S

**Comment by pedrovgs** [comment]
Hum...we are going to break a lot of projects with this update xD You are changing AdapteeCollection interface. I guess the change is positive and it worth, do you need this change for your project or is just a cosmetic change?

**Comment by raycoarana** [comment]
It's for Baindo, with this I can create a observable list that implements
AdapteeCollection without having to implement a lot of simple methods
calling the inner list. It's more efficient this way too.

**Comment by pedrovgs** [comment]
I understand what are you doing in this PR xD I was just saying we are going to break some library clients code, but it's ok for me. Fix your build problems and I'll merge this pull request and publish a new version to Maven Central.

Thanks!

**Comment by raycoarana** [comment]
Ready to integrate!

**Comment by pedrovgs** [comment]
Thanks @raycoarana !! This PR is really cool!

**Pull request merged**
